"""
Auto-generates a thin Markdown wrapper for every PDF under docs/ so that
PDFs appear in the sidebar and render inline via <iframe> when clicked.

The generated .md files are created in on_config (before MkDocs collects
pages) and cleaned up in on_shutdown so they never get committed.
"""

import os
import re
from pathlib import Path
from urllib.parse import quote

_GENERATED_TAG = "<!-- auto-generated by pdf_pages hook -->"
_generated_files: list[Path] = []


def _pretty_title(pdf_name: str) -> str:
    """Turn 'Some-File_v2.pdf' into 'Some File v2'."""
    stem = Path(pdf_name).stem
    stem = stem.replace("-", " ").replace("_", " ")
    stem = re.sub(r"\s+", " ", stem).strip()
    return stem


def on_config(config):
    docs_dir = Path(config["docs_dir"])

    for pdf_path in sorted(docs_dir.rglob("*.pdf")):
        md_path = pdf_path.with_suffix(".md")

        if md_path.exists():
            content = md_path.read_text(encoding="utf-8", errors="ignore")
            if _GENERATED_TAG not in content:
                continue

        pdf_filename = quote(pdf_path.name)
        title = _pretty_title(pdf_path.name)

        md_content = f"""{_GENERATED_TAG}
---
title: "{title}"
---

# {title}

<iframe src="{pdf_filename}" width="100%" height="800px" style="border: 1px solid #ccc;">
    <p><a href="{pdf_filename}">Download {title} (PDF)</a></p>
</iframe>
"""
        md_path.write_text(md_content, encoding="utf-8")
        _generated_files.append(md_path)


def on_shutdown():
    for md_path in _generated_files:
        try:
            md_path.unlink()
        except OSError:
            pass
    _generated_files.clear()
